# Generated by Django 5.1.2 on 2024-10-21 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='created_date',
            new_name='data_hora',
        ),
        migrations.AddField(
            model_name='agenda',
            name='valor',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='descricao_sevico',
            field=models.TextField(max_length=500),
        ),
    ]
