# Generated by Django 5.1.2 on 2024-10-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agenda_sobrenome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='descricao_sevico',
            new_name='descricao_servico',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='name',
            new_name='nome',
        ),
    ]
