# Generated by Django 5.1.2 on 2024-10-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_rename_descricao_sevico_agenda_descricao_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%y/%m/'),
        ),
    ]
