# Generated by Django 5.1.2 on 2024-10-21 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_sexo_agenda_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faixa_Etaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='faixa_etaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.faixa_etaria'),
        ),
    ]
