# Generated by Django 5.1.2 on 2024-10-21 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_agenda_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='faixa_etaria',
            options={'verbose_name': 'Faixa Etária', 'verbose_name_plural': 'Faixa Etárias'},
        ),
        migrations.AlterModelOptions(
            name='sexo',
            options={'verbose_name': 'Sexo', 'verbose_name_plural': 'Sexos'},
        ),
    ]
