# Generated by Django 5.1.2 on 2024-10-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_agenda_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='owner',
            new_name='proprietario',
        ),
    ]
