# Generated by Django 5.1.2 on 2024-10-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_rename_owner_agenda_proprietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
